# Generated by Django 5.2.4 on 2025-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csd',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
