# Generated by Django 5.2.4 on 2025-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0002_alter_csd_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='csd',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
