# Generated by Django 5.2.4 on 2025-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0003_csd_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='csd',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
