# Generated by Django 5.2.4 on 2025-07-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0004_csd_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csd',
            name='photo',
        ),
    ]
