# Generated by Django 5.2.4 on 2025-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0005_remove_csd_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='csd',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
